# -*- coding: utf-8 -*-
"""Copy of Assignment 3 python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19nkRq1xhwczszY-dcDvFPa41w6_7okPm

## ASSIGNMENT 3 CONDITIONAL AND LOOPING STATEMENTS

**Exercise 1: MonthNames.py**
"""

month = int(input("Enter the month (1-12): "))

if month == 1:
    print("Month 1 is January")
elif month == 2:
    print("Month 2 is February")
elif month == 3:
    print("Month 3 is March")
elif month == 4:
    print("Month 4 is April")
elif month == 5:
    print("Month 5 is May")
elif month == 6:
    print("Month 6 is June")
elif month == 7:
    print("Month 7 is July")
elif month == 8:
    print("Month 8 is August")
elif month == 9:
    print("Month 9 is September")
elif month == 10:
    print("Month 10 is October")
elif month == 11:
    print("Month 11 is November")
elif month == 12:
    print("Month 12 is December")
else:
    print("Invalid month! Please enter a number between 1 and 12.")

"""**Exercise 2: Cinema Ticket Price**"""

age = int(input("Enter your age: "))
price = 6  # Full price

if age < 16:
    price /= 2  # Half price
elif age >= 60:
    price /= 3  # One-third price

print(f"Your ticket costs £{price:.2f}")

age = int(input("Enter your age: "))
price = 6  # Full price

if age < 16:
    price /= 2  # Half price
elif age >= 60:
    price /= 3  # One-third price

print(f"Your ticket costs £{price:.2f}")

age = int(input("Enter your age: "))
price = 6  # Full price

if age < 16:
    price /= 2  # Half price
elif age >= 60:
    price /= 3  # One-third price

print(f"Your ticket costs £{price:.2f}")

"""**Exercise 3: BodyMassIndex.py**"""

weight = float(input("Enter your weight in (kg): "))
height = float(input("Enter your height in (m): "))

bmi = weight / (height ** 2)

if bmi < 18.5:
    category = "Underweight"
elif bmi < 25:
    category = "Normal"
elif bmi < 30:
    category = "Overweight"
else:
    category = "Obese"

print(f"Your BMI is: {bmi:.2f}")
print(f"You are in the '{category}' range.")

"""**Exercise 4: Greatest of Three Numbers**"""

a = int(input("Enter first number: "))
b = int(input("Enter second number: "))
c = int(input("Enter third number: "))

if a >= b and a >= c:
    greatest = a
elif b >= a and b >= c:
    greatest = b
else:
    greatest = c

print(f"The greatest number is {greatest}")

"""**Exercise 5: Factorial Using Loops**"""

num = int(input("Enter a number: "))
factorial = 1

for i in range(1, num + 1):  # Loop from 1 to num
    factorial *= i  # Multiply each number to factorial

print(f"Factorial of {num} is {factorial}")

"""**Exercise 6: Reverse a Number Using While Loop**"""

num = int(input("Enter a number: "))
reverse = 0

while num > 0:
    digit = num % 10
    reverse = reverse * 10 + digit
    num //= 10

print(f"Reversed number: {reverse}")

"""**Exercise 7: Finding Multiples of a Number**"""

num = int(input("Enter a number: "))
limit = int(input("Enter the range limit: "))

for i in range(1, limit + 1):
    print(num * i)

"""**Exercise 8: Loop Until 'done' is Enteredt**"""

while True:
    value = input(": ")
    if value == "done":
        print("Done")
        break
    print(value)

"""**Exercise 9: FizzBuzz**"""

for i in range(1, 11):
    if i % 3 == 0 and i % 5 == 0:
        print("FizzBuzz")
    elif i % 3 == 0:
        print("Fizz")
    elif i % 5 == 0:
        print("Buzz")
    else:
        print(i)

"""**Exercise 10: Number Pattern**"""

for i in range(5, 0, -1):  # Loop from 5 to 1
    for j in range(i, 0, -1):  # Print numbers in decreasing order
        print(j, end=" ")
    print()  # Move to the next line after each row

